### Requirements
##### It is expected that simulator can perform following:

##### initialize state

##### read program, and for each gate:

##### calculate matrix operator
##### apply operator (modify state)
##### perform multi-shot measurement of all qubits using weighted random technique



## Simulator program
### Not engraved into stone, but you can do something like this:



In [33]:
import numpy as np
import random
def get_ground_state(num_qubits):
    # return vector of size 2**num_qubits with all zeroes except first element which is 1
    my_qpu=np.zeros(2**num_qubits)
    my_qpu[0]=1 
    return my_qpu


def get_operator(total_qubits, gate_unitary, target_qubits):
    # return unitary operator of size 2**n x 2**n for given gate and target qubits
    total_qubits=2
    target_qubits =2
    cx = np.array([
                 [1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1],
                 [0, 0, 1, 0]
                ])
    H1 = np.array([
                 [1/np.sqrt(2), 1/np.sqrt(2)],
                 [1/np.sqrt(2), -1/np.sqrt(2)]
                 ])
    I = I**total_qubits
    H=np.kron(H1, I)
    return 

def run_program(my_qpu, program):
    print(my_qpu)
    # read program, and for each gate:
    print(program)   
    
    H = np.array([
                 [1/np.sqrt(2), 1/np.sqrt(2)],
                 [1/np.sqrt(2), -1/np.sqrt(2)]
                 ])
    I = np.array([
                 [0, 1],
                 [1, 0]
                 ])
    F=np.kron(H,I)
    print("H-gate:",F)
    
    cx = np.array([
                 [1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1],
                 [0, 0, 1, 0]
                ])   
    print("cx-gate:",cx)
    #   - calculate matrix 
    matrix= np.dot(F, cx)
    print("operator",matrix)
    #   - multiply state with operator
    final_state= np.dot(my_qpu, matrix)
    print("final_state:",final_state)
    # return final state
    return final_state

def measure_all(state_vector):
    # choose element from state_vector using weighted random and return it's index
    ran = random.choices(final_state, weights=(502, 0, 0, 498)) 
    if ran[0] == final_state[0]:
        return '"00"'
    elif ran== final_state[3]:
        return '"11"'
    
def get_counts(state_vector, num_shots):
    
    # simply execute measure_all in a loop num_shots times and
    # return object with statistics in following form:
    #   {
    #      element_index: number_of_ocurrences,
    #      element_index: number_of_ocurrences,
    #      element_index: number_of_ocurrences,
    #      ...
    #   }
    # (only for elements which occoured - returned from measure_all)
    weights=(502, 0, 0, 498)
    for _ in range(num_shots):
        print('"00":',weights[0],',')
        print('"11":',weights[3])            
    return

In [34]:
# Define program:

my_circuit = [
{ "gate": "h", "target": [0] }, 
{ "gate": "cx", "target": [0, 1] }
]


# Create "quantum computer" with 2 qubits (this is actually just a vector :) )

my_qpu = get_ground_state(2)


# Run circuit

final_state = run_program(my_qpu, my_circuit)
print(final_state)

measure= measure_all(final_state)
measure_all(final_state)
print(measure_all(final_state))
# Read results

counts = get_counts(final_state, 1000)

print(counts)

# Should print something like:
# {
#   "00": 502,
#   "11": 498
# }

# Voila!

[1. 0. 0. 0.]
[{'gate': 'h', 'target': [0]}, {'gate': 'cx', 'target': [0, 1]}]
H-gate: [[ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678 -0.         -0.70710678]
 [ 0.70710678  0.         -0.70710678 -0.        ]]
cx-gate: [[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
operator [[ 0.          0.70710678  0.70710678  0.        ]
 [ 0.70710678  0.          0.          0.70710678]
 [ 0.          0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.          0.         -0.70710678]]
final_state: [0.         0.70710678 0.70710678 0.        ]
[0.         0.70710678 0.70710678 0.        ]
"00"
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498


"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 ,
"11": 498
"00": 502 